export const LIUM_OPTIONS = {
  actorRoles: [
    'Project Developer',
    'Financier',
    'Risk Provider',
    'Securities Agent',
    'Portfolio Manager',
    'Utility',
    'EdgeGrid Operator',
    'QSE / Market Participant',
    'DC Operator',
    'Telemetry Provider',
    'LIUM Admin',
  ],
  revenueTypes: [
    'Time-of-Use Arbitrage',
    'Energy Savings',
    'Demand Charge Savings',
    'PPA Revenue',
    'ESA Revenue',
    'BESPA Capacity Payment',
    'Tolling Revenue',
    'Ancillary Services',
    'Frequency Regulation',
    'Responsive Reserve',
    'ECRS',
    'Non-Spin Reserve',
    'Emergency Response Service',
    '4CP Reduction',
    'REC Revenue',
    'Carbon Credit Revenue',
    'Tax Credit / ITC',
    'VGF / Subsidy',
    'Capacity Payment',
    'Grid Deferral Payment',
    'Reliability / Resilience Value',
  ],
}
